// flow-typed signature: e25eb7c2ec9bc30a55279351595bf653
// flow-typed version: <<STUB>>/babel-engine-plugin_v^0.2.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-engine-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-engine-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-engine-plugin/lib/babel-module-template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-engine-plugin/index' {
  declare module.exports: $Exports<'babel-engine-plugin'>;
}
declare module 'babel-engine-plugin/index.js' {
  declare module.exports: $Exports<'babel-engine-plugin'>;
}
declare module 'babel-engine-plugin/lib/babel-module-template.js' {
  declare module.exports: $Exports<'babel-engine-plugin/lib/babel-module-template'>;
}
