// flow-typed signature: b35d5acdc7582928338be58ddc4d2a73
// flow-typed version: <<STUB>>/brace-expansion-parser_v^1.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brace-expansion-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brace-expansion-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brace-expansion-parser/lib/expand' {
  declare module.exports: any;
}

declare module 'brace-expansion-parser/lib/expressions' {
  declare module.exports: any;
}

declare module 'brace-expansion-parser/lib/index' {
  declare module.exports: any;
}

declare module 'brace-expansion-parser/lib/lex' {
  declare module.exports: any;
}

declare module 'brace-expansion-parser/lib/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brace-expansion-parser/lib/expand.js' {
  declare module.exports: $Exports<'brace-expansion-parser/lib/expand'>;
}
declare module 'brace-expansion-parser/lib/expressions.js' {
  declare module.exports: $Exports<'brace-expansion-parser/lib/expressions'>;
}
declare module 'brace-expansion-parser/lib/index.js' {
  declare module.exports: $Exports<'brace-expansion-parser/lib/index'>;
}
declare module 'brace-expansion-parser/lib/lex.js' {
  declare module.exports: $Exports<'brace-expansion-parser/lib/lex'>;
}
declare module 'brace-expansion-parser/lib/parse.js' {
  declare module.exports: $Exports<'brace-expansion-parser/lib/parse'>;
}
