// flow-typed signature: 14022ca97476542adfc1fc8d852e5cae
// flow-typed version: <<STUB>>/copy-text-to-clipboard_v^1.0.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-text-to-clipboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-text-to-clipboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'copy-text-to-clipboard/index' {
  declare module.exports: $Exports<'copy-text-to-clipboard'>;
}
declare module 'copy-text-to-clipboard/index.js' {
  declare module.exports: $Exports<'copy-text-to-clipboard'>;
}
