// flow-typed signature: e7906e7f073fd0a6a5276489719019f3
// flow-typed version: <<STUB>>/share-url_v^1.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'share-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'share-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'share-url/neon/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'share-url/index' {
  declare module.exports: $Exports<'share-url'>;
}
declare module 'share-url/index.js' {
  declare module.exports: $Exports<'share-url'>;
}
declare module 'share-url/neon/index.js' {
  declare module.exports: $Exports<'share-url/neon/index'>;
}
